name: sweden_property_prices_ci
##### uncomment the below lines to enable this workflow #####
#on:
#  push:
#    branches:
#      - main
#  workflow_run:
#    workflows: ["Web Scraping"]
#    types:
#      - completed
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML container
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1 #need for metric comparision and to add plot to the report
    steps:
      # may need to setup Node.js & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
      - uses: iterative/setup-cml@v3
      - uses: actions/checkout@v3
      - name: Configure Git to treat the repository directory as safe
        run: git config --global --add safe.directory /__w/sweden_property_prediction/sweden_property_prediction
      - name: Train model
        env:
          DB_SQL: ${{ secrets.DATABSE_SQL }}
          DB_NAME: ${{ secrets.DATABSE_NAME }}
          DB_PORT: ${{ secrets.DATABASE_PORT }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #report the diff
          echo "##Comparision with main branch model" > report.md 
          git fetch --prune
          dvc metrics diff main --targets metrics.json --show-md >> report.md

          echo "##Data Viz" >> report.md
          echo "![](./Learning_curves.png)" >> report.md
          echo "![](./residuals.png)" >> report.md



          cml comment create report.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add encoding_dict.pkl model.pkl scaler.pkl metrics.json 
          git commit -m "Add model artifacts"
          git push origin HEAD:main
